# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=200),
        ),
    ]
