# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost_app', '0003_auto_20180210_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
